### ISSUE TITLE
i3lock -c 000000 breaks

### ISSUE THREAD

**Issue by Raymo111** [Raymo111/i3lock-color#161]
@bendardenne can you take a look?

**Comment by bendardenne** [comment]
Works fine on my end. Is there more info? What breaks? Is it crashing? Doesn't work? Are there other options being used?

**Comment by Raymo111** [comment]
@bendardenne When I run
```
$ i3lock -c 000000
```
I get
```
i3lock: color is invalid, color must be given in 3 or 4-byte format: rrggbb[aa]
```
```
$ i3lock -v
i3lock: version aur-9ada23e (2020-05-14) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
```
Running a freshly built version I get:
```
$ ./i3lock -c 000000
=================================================================
==117005==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffc18fcb220 at pc 0x7f24c631995e bp 0x7ffc18fca3b0 sp 0x7ffc18fc9b58
READ of size 9 at 0x7ffc18fcb220 thread T0
    #0 0x7f24c631995d in __interceptor_strlen /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:370
    #1 0x55e0e9c5a4e4 in main ../../i3lock-color/i3lock.c:1592
    #2 0x7f24c5c00001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #3 0x55e0e9c5210d in _start (/home/raymo/Git/i3lock-color/build/i3lock+0x1410d)

Address 0x7ffc18fcb220 is located in stack of thread T0 at offset 3488 in frame
    #0 0x55e0e9c59b84 in main ../../i3lock-color/i3lock.c:1359

  This frame has 26 object(s):
    [32, 36) 'longoptind' (line 1370)
    [48, 52) 'screennr' (line 2079)
    [64, 72) 's' (line 2294)
    [96, 112) 'conv' (line 1366)
    [128, 144) 'ts' (line 2293)
    [160, 164) '<unknown>'
    [176, 180) '<unknown>'
    [192, 3360) 'longopts' (line 1371)
    [3488, 3497) 'padded' (line 1592) <== Memory access at offset 3488 is inside this variable
    [3520, 3529) 'padded' (line 1595)
    [3552, 3561) 'padded' (line 1598)
    [3584, 3593) 'padded' (line 1601)
    [3616, 3625) 'padded' (line 1604)
    [3648, 3657) 'padded' (line 1607)
    [3680, 3689) 'padded' (line 1610)
    [3712, 3721) 'padded' (line 1613)
    [3744, 3753) 'padded' (line 1616)
    [3776, 3785) 'padded' (line 1619)
    [3808, 3817) 'padded' (line 1622)
    [3840, 3849) 'padded' (line 1625)
    [3872, 3881) 'padded' (line 1628)
    [3904, 3913) 'padded' (line 1631)
    [3936, 3945) 'padded' (line 1634)
    [3968, 3977) 'padded' (line 1637)
    [4000, 4009) 'padded' (line 1640)
    [4032, 4041) 'padded' (line 1992)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:370 in __interceptor_strlen
Shadow bytes around the buggy address:
  0x1000031f15f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000031f1600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000031f1610: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000031f1620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000031f1630: 00 00 00 00 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2
=>0x1000031f1640: f2 f2 f2 f2[f8]f8 f2 f2 00 01 f2 f2 00 01 f2 f2
  0x1000031f1650: 00 01 f2 f2 00 01 f2 f2 00 01 f2 f2 00 01 f2 f2
  0x1000031f1660: 00 01 f2 f2 00 01 f2 f2 00 01 f2 f2 00 01 f2 f2
  0x1000031f1670: 00 01 f2 f2 00 01 f2 f2 00 01 f2 f2 00 01 f2 f2
  0x1000031f1680: 00 01 f2 f2 00 01 f2 f2 00 01 f3 f3 00 00 00 00
  0x1000031f1690: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==117005==ABORTING
```

**Comment by bendardenne** [comment]
Oh, that's right, padded has to be declared before the if scope. 
I'll create a PR for the fix.
