### ISSUE TITLE
==8521==ERROR: LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by weberval** [Raymo111/i3lock-color#57]
### Expected behaviour
Fork and run as intended.

### Actual behaviour
i3lock-color seems to run as expected, but it doesn't fork and produces the following error: 

```
==8521==ERROR:` LeakSanitizer: detected memory leaks

Direct leak of 512 byte(s) in 2 object(s) allocated from:
    #0 0x7f2aa5c49ae9 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x7f2aa20967ee  (/usr/lib/libfontconfig.so.1+0x1d7ee)

Indirect leak of 128 byte(s) in 4 object(s) allocated from:
    #0 0x7f2aa5c49ce1 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:70
    #1 0x7f2aa2096ed9  (/usr/lib/libfontconfig.so.1+0x1ded9)

Indirect leak of 20 byte(s) in 2 object(s) allocated from:
    #0 0x7f2aa5be03b1 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:560
    #1 0x7f2aa20961f5 in FcValueSave (/usr/lib/libfontconfig.so.1+0x1d1f5)

SUMMARY: AddressSanitizer: 660 byte(s) leaked in 8 allocation(s).
```

### Steps to reproduce this behaviour
Just execute i3lock

### System:
OS: Arch
i3lock-color version: 2.10.1c-non-git

**Comment by PandorasFox** [comment]
See https://github.com/i3/i3lock/issues/167
