### ISSUE TITLE
fontconfig 2.13 memory leaks

### ISSUE THREAD

**Issue by PandorasFox** [Raymo111/i3lock-color#88]
It appears that there's fontconfig memory leaks (yet again) with fontconfig 2.13. I'm not sure if this is because of stuff in i3lock, or stuff in fontconfig.

I'm leaning towards the latter (when I built my local copy of fontconfig, ASAN complained about _several_ memory leaks when doing the post-install fontconfig cache hooks), but I'll still investigate and see if I can fix the issue _somewhere_.

**Comment by PandorasFox** [comment]
```
┌arcana@lapfox-(~/i3lock-color)  [130] 
└> cat ./asan_suppressions.txt                                                                           
# fontconfig....
leak:libfontconfig
┌arcana@lapfox-(~/i3lock-color)   
└> LSAN_OPTIONS=suppressions=/home/arcana/i3lock-color/asan_suppressions.txt ./lock.sh
-----------------------------------------------------
Suppressions used:
  count      bytes template
     29       2849 libfontconfig
-----------------------------------------------------

┌arcana@lapfox-(~/i3lock-color)   
└> -----------------------------------------------------
-----------------------------------------------------
Suppressions used:
Suppressions used:
  count      bytes template
  count      bytes template
     29       2849 libfontconfig
     35       3473 libfontconfig
-----------------------------------------------------

-----------------------------------------------------


┌arcana@lapfox-(~/i3lock-color)   
└> 
```

This can be suppressed and I'll be doing this in testing.

I will leave this open, mostly in the hopes that people see it instead of creating new issues...

**Comment by re1** [comment]
Same problem here with `fontconfig-2.13.0+10+g58f5285-1` on Arch Linux (just installed from AUR).

```
=================================================================
==27075==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 512 byte(s) in 2 object(s) allocated from:
    #0 0x7fb644f81d99 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x7fb6434356ee  (/usr/lib/libfontconfig.so.1+0x1f6ee)

Direct leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7fb644f81d99 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x7fb643434d7e in FcPatternCreate (/usr/lib/libfontconfig.so.1+0x1ed7e)

Indirect leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7fb644f81fc1 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:95
    #1 0x7fb643435dd9  (/usr/lib/libfontconfig.so.1+0x1fdd9)

SUMMARY: AddressSanitizer: 624 byte(s) leaked in 6 allocation(s).
```

**Comment by PandorasFox** [comment]
Fixed with a subsequent fontconfig release (unsure which one, though)
